"""Migracion inicial, roles y usuarios

Revision ID: 8c5c6ad95756
Revises: 
Create Date: 2025-03-16 09:51:31.143993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c5c6ad95756'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='login'
    )
    op.create_index(op.f('ix_login_roles_id'), 'roles', ['id'], unique=False, schema='login')
    op.create_index(op.f('ix_login_roles_name'), 'roles', ['name'], unique=True, schema='login')
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['login.roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='login'
    )
    op.create_index(op.f('ix_login_users_email'), 'users', ['email'], unique=True, schema='login')
    op.create_index(op.f('ix_login_users_id'), 'users', ['id'], unique=False, schema='login')
    op.create_index(op.f('ix_login_users_username'), 'users', ['username'], unique=True, schema='login')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_login_users_username'), table_name='users', schema='login')
    op.drop_index(op.f('ix_login_users_id'), table_name='users', schema='login')
    op.drop_index(op.f('ix_login_users_email'), table_name='users', schema='login')
    op.drop_table('users', schema='login')
    op.drop_index(op.f('ix_login_roles_name'), table_name='roles', schema='login')
    op.drop_index(op.f('ix_login_roles_id'), table_name='roles', schema='login')
    op.drop_table('roles', schema='login')
    # ### end Alembic commands ###
